# Generated by Django 5.1.1 on 2024-10-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klemapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pays',
        ),
    ]
